name: flutter_clean_mvvm
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  flutter_svg: ^2.0.9
  retrofit: ^4.0.3
  #  analyzer: ^6.2.0
  dio: ^5.4.0
  json_serializable: ^6.7.1
  flutter_screenutil: ^5.9.0
  very_good_analysis: ^5.1.0

  json_annotation: ^4.8.1
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2
  freezed: ^2.4.6
  get_it: ^7.6.6
  lottie: ^3.0.0
  country_code_picker: ^3.0.0
  image_picker: ^1.0.6
  rxdart: ^0.27.7
  carousel_slider: ^4.2.1
  easy_localization: ^3.0.3
  flutter_phoenix: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.0.6
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/splash_logo.png
    - assets/images/onboarding_logo1.svg
    - assets/images/onboarding_logo2.svg
    - assets/images/onboarding_logo3.svg
    - assets/images/onboarding_logo4.svg
    - assets/images/hollow_circle_ic.svg
    - assets/images/solid_circle_ic.svg
    - assets/images/left_arrow_ic.svg
    - assets/images/right_arrow_ic.svg
    - assets/images/photo-camera.svg
    - assets/images/change_lang_ic.svg
    - assets/images/contact_us_ic.svg
    - assets/images/invite_friends_ic.svg
    - assets/images/logout_ic.svg
    - assets/images/right_arrow_settings_ic.svg
    - assets/json/loading.json
    - assets/json/error.json
    - assets/json/empty.json
    - assets/json/success.json
    - assets/translations/ar-SA.json
    - assets/translations/en-US.json
  #jjh
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
